### ISSUE TITLE
rack_iam integration

### ISSUE THREAD

**Issue by cwgem** [rackerlabs/jetstream#62]
This issue is for integrating [rack_iam](https://github.com/rackerlabs/rack_iam_oss) into jetstream for use with creation of IAM related components. In essence rack_iam creates a CF compatible dictionary which can be used as properties for various high level troposphere IAM objects. It has the following benefits:

* An extensive test suite
* API documentation required for all modules, objects, and methods under the rack_iam folder
* Run against flake8 and flake8 docstring to ensure as much valid code structure as possible
* Much more relaxed in terms of accepting input (for those who wish more constraints and validations awacs will still be available) 
* Object attributes are standard and this enables easier code completion in IDEs

awacs will still be kept as both an alternative as well as a safeguard in the event anything happens to rack_iam. The reverse holds true as well.

**Comment by jarosser06** [comment]
Jetstream is strictly a Troposphere client it doesn't have anything related to awacs. Adding an IAM policy generator is out of scope for this project.  

The fact that awacs is in the requirements is likely a hold over from a previous incarnation of the project and can be removed.

**Comment by horacio3** [comment]
We should probably pull the awacs requirements as they are not being used in this project.

**Comment by cwgem** [comment]
The only fear I have in pulling it is that users rely on it for their dep resolution ( yes I know that's not how it should be but still ). Originally I thought it might be needed due to the way that jetstream loads the template classes (not troposphere's, but the user template classes) but that was probably just overthinking the coupling between the two. 

At any rate I can still pull the awacs dep just want to make sure that the potential dep breakage might be an issue.
