### ISSUE TITLE
troposphere-2.0.0 depend update (review possible breaking change)

### ISSUE THREAD

**Issue by cwgem** [rackerlabs/jetstream#66]
From the release notes:

## 2.0.0 (2017-10-07)
- Note: the s3.Bucket change (#844) *may* cause a breaking change for non-named arguments.
- Add DefinitionBody to serverless API (#822)
- Adding kinesis stream source to firehose (#823)
- Add `Event::Rule::Target::EcsParameters` (#824)
- Add S3 Transfer Acceleration to AWS::S3::Bucket (#833)
- Add AvailabilityZone property to TargetDescription (#834)
- Add Tags to NATGateway (#835)
- Add ResourceLifecycleConfig to ElasticBeanstalk (#836)
- Add AWS::Athena::NamedQuery (#837)
- Added platformArn to Environment and ConfigurationTemplate (#839)
- Events target (fixes #830) (#840)
- Refactor s3.Bucket to remove custom __init__() and add tests (#844)
- Be more explicit on the use of the Tags object for Tags (#845)

Need to check and see what the first note is about though

**Comment by horacio3** [comment]
Waiting on:
https://github.com/cloudtools/troposphere/issues/846

**Comment by twistedgrim** [comment]
Looks like a new commit to master has fixed the issue. 
https://github.com/rackerlabs/jetstream/issues/66 `Thank you for the issue. From my testing 1.9.6 and 2.0.0 both fail with ValueError when using a Ref(). Your use case is valid and I just pushed a fix onto master (82f0bee) for you to test.`
No new release has been cut though.

**Comment by gdelvalle** [comment]
we run > 2.0 so I'm gonna infer this became moot per earlier comment
