### ISSUE TITLE
Versioning Metadata For Template Validation

### ISSUE THREAD

**Issue by cwgem** [rackerlabs/jetstream#85]
When jetstream generates templates, it does not include any kind of versioning to make it quickly apparent when an existing template and a generated template differ. To rectify this the plan is to make a metadata value which can have a freeform string to be used for versioning (such as a version number, hash value, timestamp). 

1. Update the comparison code. Currently the code to compare old and new templates uses `cmp`, which is deprecated in python 3. Our initial research shows that == instead looks promising to handle both python 2 and 3 accordingly, without a lot of effort to update code.
2. Create code which removes various components from the resulting old/new object content. My initial thought is to use a list of keys in some constant so we can remove more if we need to.
3. Create CLI flags in jetstream to both add the date/hash and decide what the format of it should look like. These will set options for now and not update any code just yet. This is to avoid breaking default configurations which may not expect this.
4. Create the code which produces the string from the CLI options to use for our indicator

I'm thinking we can have a single PR with the above broken down into 4 functional commits to get this working.

**Comment by martinb3** [comment]
Curious about the use case for this over something like `git status` showing what files have been changed?

**Comment by jarosser06** [comment]
Item number 1 is completely separate from this particular suggestion and should be treated as such. As for injecting metadata, I think it would make more sense to allow passing arbitrary key values that are then populated into a template than specifying something specific. 

You could then add whatever metadata/versioning you want via the CLI.
```
jetstream -m my_templates --metadata "Version=v0.1.0"
```

This would keep Jetstream from being too opinionated and could be a good benefit for others that may want to inject different metadata at template generate time.

**Comment by jarosser06** [comment]
Sounds logical, I'm not 100% sold on using a Jetstream top level metadata key but I'll review when a PR is created.

**Comment by cwgem** [comment]
Closing this out as the related PR is merged in. The `cmp` issue will probably be part of an overall Python 3 migration plan and as such will be handled differently.
