### ISSUE TITLE
Documentation Generation Code Path Issue

### ISSUE THREAD

**Issue by cwgem** [rackerlabs/jetstream#98]
Currently the `newer` method of all the publisher classes is executed when dealing with both JSON templates and markdown generation. Unfortunately the documentation part hits through a logical branch of the JSON parser. Essentially if the JSON parser can't deal with the content it just loads it as a string and compares that way. When trying on Python 3 it appears that the exception path isn't get hit in the newer method for incorrect JSON encoding leading to:

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This is not what the try/catch is expecting leading to the markdown logic failing out as a standard JSON error. This will make dual python 2/3 support very difficult. Instead I propose:

1. Breaking out the generic file loading as `load_content` which returns a file pointer, usable by both standard file reads and JSON loading
2. Creation of `publish_template` and `publish_documentation` which utilizes `load_content` and handles the parsing separately
3. Update the CLI code to use these new calls

Another possible issue is how to handle the `load_template` part in dealing with both JSON and YAML at the same time. As our internal use constitutes JSON templates we haven't had much of a need to concern on the YAML part. Given that AWS has many official YAML templates however, it would probably be good to consider making this work a bit more smoothly at some point (as a separate issue).

**Comment by johnctitus** [comment]
Can we just add an additional except clause to catch the new exception we are seeing in python3?  Might be easier than writing out a completely new path.

**Comment by cwgem** [comment]
For more context:

Python2:

`ValueError: No JSON object could be decoded`

Python3:

`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

According to [the docs](https://docs.python.org/3/library/json.html#exceptions) `json.decoder.JSONDecodeError` is a subclass of `ValueError`. With that in mind I think it's fine to simply generalize the processing as `ValueError` without trying to parse out the exception string, which is causing the issue at hand.
